import { app, BrowserWindow, ipcMain, screen, session, shell } from 'electron'
import type { IpcMainInvokeEvent, WebContents } from 'electron'
import * as fs from 'fs'
import * as path from 'path'
import { runCapture, wantsCapture } from './capture'

/**
 * The default window, sized so the farm actually gets to draw at 2x.
 *
 * The farm upscales by whole numbers only, so it takes the largest integer that fits and
 * drops straight from 2x to 1x the moment it is one pixel short. This window used to be
 * exactly 1280x896 -- 2x the 640x448 framebuffer -- which would have been right if the
 * game were the whole window. It is not: the shell puts a title bar, a tab strip and a
 * status line inside that content box, and they are 32, 40 and 25 pixels tall. The farm
 * panel was therefore 1280x801, 801 is not 896, and the game rendered at 1x in the middle
 * of a very large black field.
 *
 * So the height is the framebuffer at 2x plus that chrome, with a little slack, and the
 * whole thing is clamped to the work area further down for a screen too small to hold it.
 */
// The main process compiles with its own rootDir and cannot import from `src`, so the
// framebuffer is mirrored here. `tests/window-size.test.ts` fails if the two ever differ.
const LOGICAL_W = 640
const LOGICAL_H = 448
const CHROME_H = 97
const WINDOW_W = LOGICAL_W * 2
const WINDOW_H = LOGICAL_H * 2 + CHROME_H + 8
const MIN_W = LOGICAL_W
const MIN_H = LOGICAL_H + CHROME_H

/** PAL.ink — the letterbox colour, so the window never flashes white. */
const INK = '#1b1a24'

const CSP = [
  "default-src 'self'",
  "script-src 'self'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data:",
  "connect-src 'self'",
].join('; ')

const DEV_SERVER_URL = process.env.VITE_DEV_SERVER_URL ?? ''

/** Generous ceiling on an incoming save. A full farm serialises to a fraction of this. */
const MAX_SAVE_BYTES = 4 * 1024 * 1024

function saveFile(): string {
  return path.join(app.getPath('userData'), 'save.json')
}

async function readSaveFile(): Promise<string | null> {
  try {
    const text = await fs.promises.readFile(saveFile(), 'utf8')
    return text.length > 0 ? text : null
  } catch {
    return null
  }
}

/** Writes through a temp file so a crash mid-write cannot leave a half-written save. */
async function writeSaveFile(json: string): Promise<boolean> {
  const file = saveFile()
  const temp = `${file}.tmp`
  try {
    await fs.promises.mkdir(path.dirname(file), { recursive: true })
    await fs.promises.writeFile(temp, json, 'utf8')
    await fs.promises.rename(temp, file)
    return true
  } catch {
    try {
      await fs.promises.rm(temp, { force: true })
    } catch {
      // Nothing to clean up, or the disk is refusing us entirely. Either way, report failure.
    }
    return false
  }
}

async function clearSaveFile(): Promise<boolean> {
  try {
    await fs.promises.rm(saveFile(), { force: true })
    return true
  } catch {
    return false
  }
}

function parseUrl(raw: string): URL | null {
  try {
    return new URL(raw)
  } catch {
    return null
  }
}

/** True only for the page this app actually serves: the dev server, or a local file. */
function isAppUrl(raw: string): boolean {
  const url = parseUrl(raw)
  if (!url) return false
  if (DEV_SERVER_URL) {
    const dev = parseUrl(DEV_SERVER_URL)
    return dev !== null && url.origin === dev.origin
  }
  return url.protocol === 'file:'
}

function openExternally(raw: string): void {
  const url = parseUrl(raw)
  if (!url || (url.protocol !== 'https:' && url.protocol !== 'http:')) return
  shell.openExternal(raw).catch(() => undefined)
}

function harden(contents: WebContents): void {
  contents.setWindowOpenHandler(({ url }) => {
    openExternally(url)
    return { action: 'deny' }
  })
  contents.on('will-navigate', (event, url) => {
    if (isAppUrl(url)) return
    event.preventDefault()
    openExternally(url)
  })
  contents.on('will-attach-webview', (event) => {
    event.preventDefault()
  })
}

/**
 * Tells the renderer the window's maximised state changed, so the title bar's
 * maximise button can follow a double-click, a drag to the top edge, or the OS
 * doing it for us. Sent on both `maximize` and `unmaximize`.
 */
function pushMaximizedState(win: BrowserWindow): void {
  if (win.isDestroyed()) return
  win.webContents.send('window:maximized-changed', win.isMaximized())
}

/**
 * The application mark, for the window and the taskbar while running unpackaged.
 *
 * A packaged build takes its icon from the executable, which electron-builder stamps from
 * `build/icon.ico`, so this only matters for `npm start` and a dev run — but a dev run
 * showing the framework default is how a missing icon goes unnoticed until release. The
 * file is generated by `scripts/make-icon.mjs` and is not committed, so a checkout that
 * has not generated it yet simply gets no override rather than a crash.
 */
function windowIcon(): string | undefined {
  const candidate = path.join(__dirname, '..', 'build', 'icon.png')
  return fs.existsSync(candidate) ? candidate : undefined
}

/**
 * The default size, never larger than the screen it opens on.
 *
 * The window wants to be tall enough for the farm at 2x. On a laptop that is shorter than
 * that, asking for it anyway would put the status line under the taskbar, so it is clamped
 * to the work area and the farm simply draws at 1x — which is the honest outcome on a
 * screen with no room, rather than a window running off the bottom.
 */
function defaultBounds(): { width: number; height: number } {
  try {
    const work = screen.getPrimaryDisplay().workAreaSize
    return {
      width: Math.min(WINDOW_W, Math.max(MIN_W, work.width)),
      height: Math.min(WINDOW_H, Math.max(MIN_H, work.height)),
    }
  } catch {
    // No display information available; the requested size is still a reasonable default.
    return { width: WINDOW_W, height: WINDOW_H }
  }
}

function createWindow(): void {
  const bounds = defaultBounds()
  const win = new BrowserWindow({
    width: bounds.width,
    height: bounds.height,
    minWidth: MIN_W,
    minHeight: MIN_H,
    useContentSize: true,
    backgroundColor: INK,
    title: 'Sprout Hollow',
    icon: windowIcon(),
    // Frameless: src/shell/ui/titlebar.ts draws the bar and owns the controls.
    frame: false,
    autoHideMenuBar: true,
    show: false,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
      webviewTag: false,
      spellcheck: false,
      // Screenshot mode runs the window hidden; without this the game loop is
      // throttled to a crawl and every capture photographs the same frame.
      backgroundThrottling: !wantsCapture(process.argv),
    },
  })

  if (wantsCapture(process.argv)) {
    // Deliberately never shown. On a GPU-less off-screen desktop the first paint
    // never completes, so `ready-to-show` never fires — and calling show() before
    // that paint wedges the renderer outright (no dom-ready, no console, nothing).
    // Left hidden, the renderer runs normally and the canvas can be read directly.
    // `backgroundThrottling: false` keeps requestAnimationFrame ticking while hidden.
    runCapture(win, process.argv).catch((err) => {
      process.stdout.write(`capture failed: ${String(err)}\n`)
      app.exit(1)
    })
  } else {
    win.once('ready-to-show', () => win.show())
  }
  win.setMenuBarVisibility(false)
  win.on('maximize', () => pushMaximizedState(win))
  win.on('unmaximize', () => pushMaximizedState(win))
  harden(win.webContents)

  if (DEV_SERVER_URL) {
    win.loadURL(DEV_SERVER_URL).catch(() => undefined)
  } else {
    win.loadFile(path.join(__dirname, '..', 'dist', 'index.html')).catch(() => undefined)
  }
}

function registerSaveHandlers(): void {
  ipcMain.handle('save:read', () => readSaveFile())
  ipcMain.handle('save:write', (_event, json: unknown) => {
    if (typeof json !== 'string' || Buffer.byteLength(json, 'utf8') > MAX_SAVE_BYTES) {
      return Promise.resolve(false)
    }
    return writeSaveFile(json)
  })
  ipcMain.handle('save:clear', () => clearSaveFile())
}

/** The window that asked, or null if it has already gone away mid-call. */
function senderWindow(event: IpcMainInvokeEvent): BrowserWindow | null {
  const win = BrowserWindow.fromWebContents(event.sender)
  return win !== null && !win.isDestroyed() ? win : null
}

/**
 * The four channels behind the custom title bar. Each one acts on the window that
 * asked, never on a window it was handed, so a renderer cannot reach another window.
 */
function registerWindowHandlers(): void {
  ipcMain.handle('window:minimize', (event: IpcMainInvokeEvent) => {
    const win = senderWindow(event)
    if (win !== null && win.isMinimizable()) win.minimize()
  })

  ipcMain.handle('window:maximize', (event: IpcMainInvokeEvent) => {
    const win = senderWindow(event)
    if (win === null) return false
    if (win.isMaximized()) win.unmaximize()
    else if (win.isMaximizable()) win.maximize()
    return win.isMaximized()
  })

  ipcMain.handle('window:close', (event: IpcMainInvokeEvent) => {
    const win = senderWindow(event)
    if (win !== null) win.close()
  })

  ipcMain.handle('window:isMaximized', (event: IpcMainInvokeEvent) => {
    const win = senderWindow(event)
    return win !== null && win.isMaximized()
  })
}

function applySecurityHeaders(): void {
  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    const headers: Record<string, string | string[]> = { ...(details.responseHeaders ?? {}) }
    for (const key of Object.keys(headers)) {
      if (key.toLowerCase() === 'content-security-policy') delete headers[key]
    }
    headers['Content-Security-Policy'] = [CSP]
    callback({ responseHeaders: headers })
  })
  // The game needs no camera, microphone, geolocation or notifications. Ever.
  session.defaultSession.setPermissionRequestHandler((_contents, _permission, done) => done(false))
}

app.whenReady().then(
  () => {
    applySecurityHeaders()
    registerSaveHandlers()
    registerWindowHandlers()
    createWindow()

    app.on('activate', () => {
      if (BrowserWindow.getAllWindows().length === 0) createWindow()
    })
  },
  () => app.quit(),
)

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit()
})
